

FROM openjdk:17-jdk-slim

MAINTAINER darshan

COPY target/Find-Route-Server-Registry-0.0.1-SNAPSHOT.jar Find-Route-Server-Registry-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","Find-Route-Server-Registry-0.0.1-SNAPSHOT.jar"]